### ISSUE TITLE
ParserException: NDBC API: unspecified error

### ISSUE THREAD

**Issue by Thomasdht** [CDJellen/ndbc-api#26]
Hello,

When performing the same test as you do in your overview notebook : 

`df_stdmet_tplm2 = api.get_data(
    'tplm2',
    'stdmet',
    '2020-01-01',
    '2022-01-01',
    as_df=True
)`

I get the following error : 
`KeyError                                  Traceback (most recent call last)
~/.local/lib/python3.10/site-packages/ndbc_api/api/parsers/_base.py in ?(cls, responses, use_timestamp)
     32             df = df.set_index('timestamp').sort_index()
     33         except KeyError as e:
---> 34             raise ParserException from e
     35         return df

/work/softs/rh8/conda-envs/pangeo_20230613/lib/python3.10/site-packages/pandas/util/_decorators.py in ?(*args, **kwargs)
    329                     stacklevel=find_stack_level(),
    330                 )
--> 331             return func(*args, **kwargs)

/work/softs/rh8/conda-envs/pangeo_20230613/lib/python3.10/site-packages/pandas/core/frame.py in ?(self, keys, drop, append, inplace, verify_integrity)
   6010 
   6011         if missing:
-> 6012             raise KeyError(f"None of {missing} are in the columns")
   6013 

KeyError: "None of ['timestamp'] are in the columns"

The above exception was the direct cause of the following exception:

ParserException                           Traceback (most recent call last)
Cell In[15], line 1
----> 1 df_stdmet_tplm2 = api.get_data(
      2     'tplm2',
      3     'stdmet',
      4     '2020-01-01',
      5     '2022-01-01',
      6     as_df=True
      7 )

File ~/.local/lib/python3.10/site-packages/ndbc_api/ndbc_api.py:381, in NdbcApi.get_data(self, station_id, mode, start_time, end_time, use_timestamp, as_df, cols)
    378     raise RequestException(
    379         'Please supply a supported mode from `get_modes()`.')
    380 try:
--> 381     data = data_api_call(
    382         self._handler,
    383         station_id,
    384         start_time,
    385         end_time,
    386         use_timestamp,
    387     )
    388 except (ResponseException, ValueError, TypeError, KeyError) as e:
    389     raise ResponseException('Failed to handle API call.') from e

File ~/.local/lib/python3.10/site-packages/ndbc_api/api/handlers/data.py:146, in DataHandler.stdmet(cls, handler, station_id, start_time, end_time, use_timestamp)
    144 except Exception as e:
    145     raise ResponseException('Failed to execute requests.') from e
--> 146 return StdmetParser.df_from_responses(responses=resps,
    147                                       use_timestamp=use_timestamp)

File ~/.local/lib/python3.10/site-packages/ndbc_api/api/parsers/stdmet.py:17, in StdmetParser.df_from_responses(cls, responses, use_timestamp)
     13 @classmethod
     14 def df_from_responses(cls, responses: List[dict],
     15                       use_timestamp: bool) -> pd.DataFrame:
     16     return super(StdmetParser,
---> 17                  cls).df_from_responses(responses, use_timestamp)

File ~/.local/lib/python3.10/site-packages/ndbc_api/api/parsers/_base.py:34, in BaseParser.df_from_responses(cls, responses, use_timestamp)
     32     df = df.set_index('timestamp').sort_index()
     33 except KeyError as e:
---> 34     raise ParserException from e
     35 return df

ParserException: NDBC API: unspecified error`

Could you please help me know why ? Thanks !!

**Comment by CDJellen** [comment]
Thank you for the bug report @Thomasdht !  I'll look into this shortly.

It is likely the result of a change in the schema of the NDBC file server.

**Comment by CDJellen** [comment]
@Thomasdht would you be able to let me know what version of pandas you are running? You can determine this by running to run  `pip freeze | grep pandas` or equivalent. I've not been able to reproduce the bug but it could be a update to the DataFrame implementation.

**Comment by Thomasdht** [comment]
I have upgraded my environnement to python 3.9 and pandas 2.2.0 and everything works now ! Thank you very much
