### ISSUE TITLE
Consider implementing NDBC radial search

### ISSUE THREAD

**Issue by supermanzer** [CDJellen/ndbc-api#27]
The NDBC website implements a radial search centered on a set of coordinates [here](https://www.ndbc.noaa.gov/radial_search.php).  When doing my own research using NDBC buoy stations, my advisor would request I validate my findings against other data stations within N miles and I suspect the utility would be useful for other researchers as well.

**Comment by CDJellen** [comment]
That is an excellent suggestion @supermanzer ; I'll look into an implementation. If you have any other ideas for improvements or useful utilities please open another issue. Additionally, if you'd like to contribute your research (either as a notebook or a link to a publication) I would be happy to include it here for the benefit of future researchers.

I'll leave this issue open and tracked under branch `27-consider-implementing-ndbc-radial-search`.

Thanks and have an excellent rest of your day!
