### ISSUE TITLE
Conda Package

### ISSUE THREAD

**Issue by abdu558** [CDJellen/ndbc-api#29]
Are there any plans for a Conda Package?

**Comment by CDJellen** [comment]
Hello @abdu558, I'll look into developing a conda package if it would be useful to you. Please let me know if you have other suggestions for feature improvements, have a great rest of your day!

**Comment by abdu558** [comment]
Hello @CDJellen ,
Yea that would be exteremly useful and essential to me.
One other thing, the capability of getting multistation data would be useful so being able to get data of all the stations.

**Comment by CDJellen** [comment]
Hello @abdu558 ; I've made some updates in #30 to address some of these feature requests; if you have any future suggestions please feel free to open another issue!

I'll try to have the conda package up later today.

**Comment by CDJellen** [comment]
Just to follow up on this, it will take some time to get the package added to conda forge, but the `meta.yaml` file below should be sufficient to generate a conda distribution locally. 
[meta.yaml.txt](https://github.com/user-attachments/files/15756656/meta.yaml.txt)

**Comment by abdu558** [comment]
Thank you so much @CDJellen

**Comment by CDJellen** [comment]
I've created a PR to add `ndbc-api` as a conda package through conda forge; you can track the progress [here](https://github.com/conda-forge/staged-recipes/pull/26623).

Thanks again for the suggestions; I'll keep tabs on the PR but it might take a few days to merge and then become available;

**Comment by abdu558** [comment]
Thank you once again, also can you update the pip package so that the new updates are there

**Comment by CDJellen** [comment]
> Thank you once again, also can you update the pip package so that the new updates are there

I've created a new release `0.24.6.12.1` which is up on pypi and should now be available over pip. I've also updated the conda forge PR but it has yet to clear CI; either the runners are unable to reach the file (it appears to be an issue affecting all new PRs) or it'll just take some time for the most recent version to become availalble.

Thanks again and have an excellent rest of your day!

**Comment by CDJellen** [comment]
I'll keep this issue up until [the PR merges](https://github.com/conda-forge/staged-recipes/pull/26623);

**Comment by abdu558** [comment]
> > Thank you once again, also can you update the pip package so that the new updates are there
> 
> I've created a new release `0.24.6.12.1` which is up on pypi and should now be available over pip. I've also updated the conda forge PR but it has yet to clear CI; either the runners are unable to reach the file (it appears to be an issue affecting all new PRs) or it'll just take some time for the most recent version to become availalble.
> 
> Thanks again and have an excellent rest of your day!

Thank you, have a great day too!

**Comment by CDJellen** [comment]
> I'll keep this issue up until [the PR merges](https://github.com/conda-forge/staged-recipes/pull/26623);

The PR was merged in earlier today! `ndbc-api` should now be available through conda forge.

Thank you for opening this issue and please feel free to suggest new features or improvements!
