### ISSUE TITLE
get_data() error returning data from the api

### ISSUE THREAD

**Issue by thex1le** [CDJellen/ndbc-api#33]
Running the following example example from your notebook  example #29 an unspecified Parser Exception is thrown. 

Here is the example code i ran. 

from ndbc_api import NdbcApi
api = NdbcApi()
df_annapolis_met = api.get_data(
    station_ids=['tplm2', 'apam2', 44063, 'CPVM2'],
    modes=['stdmet'],
    start_time='2023-01-01',
    end_time='2024-01-01',
    as_df=True
)
print(df_annapolis_met)

Which produced the following traceback.

Traceback (most recent call last):
  File "/home/ben/.local/lib/python3.10/site-packages/ndbc_api/api/parsers/_base.py", line 32, in df_from_responses
    df = df.set_index('timestamp').sort_index()
  File "/home/ben/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/ben/pandas/core/frame.py", line 6012, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['timestamp'] are in the columns"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ben/wtf.py", line 3, in <module>
    df_annapolis_met = api.get_data(
  File "/home/ben/.local/lib/python3.10/site-packages/ndbc_api/ndbc_api.py", line 466, in get_data
    data = future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ben/.local/lib/python3.10/site-packages/ndbc_api/ndbc_api.py", line 614, in _handle_get_data
    data = data_api_call(
  File "/home/ben/.local/lib/python3.10/site-packages/ndbc_api/api/handlers/data.py", line 146, in stdmet
    return StdmetParser.df_from_responses(responses=resps,
  File "/home/ben/.local/lib/python3.10/site-packages/ndbc_api/api/parsers/stdmet.py", line 17, in df_from_responses
    cls).df_from_responses(responses, use_timestamp)
  File "/home/ben/.local/lib/python3.10/site-packages/ndbc_api/api/parsers/_base.py", line 34, in df_from_responses
    raise ParserException from e
ndbc_api.exceptions.ParserException: NDBC API: unspecified error

**Comment by CDJellen** [comment]
Hello @thex1le ; thank you for opening this issue. Unfortunately I'm not able to re-produce this error locally. It could very well be to a difference in version in the package dependencies. I've included the result of running `pip list`; if you would be able to do the same, or perhaps try testing against a clean virtual environment, I'd appreciate it.

In the mean time I'll look into using poetry for better dependency management.

Thanks and have a great rest of your day;
[list.txt](https://github.com/user-attachments/files/16103929/list.txt)

**Comment by CDJellen** [comment]
Hello @thex1le, just hoping to follow up on this and see if you're still experiencing the issue. If so please let me know and if possible drop the output of `pip list > list.txt` to help identify what package versions might be causing the issue.

Thanks and have a great rest of your day!

**Comment by thex1le** [comment]
@CDJellen apologies for the delay, I checked the same code on another system and it ran as expected so this is defiantly a lib mismatch. The system with the issue is a AWS ubuntu install which we use for some other python projects. Here are
[list.txt](https://github.com/user-attachments/files/16131650/list.txt)
 the contents of pip list as you requested.

**Comment by CDJellen** [comment]
Hello @thex1le ; I was able to reproduce the bug temporarily. Unfortunately I was not able to pinpoint exactly which package and version caused the issue. I was able to get the `ndbc-api` package working with the specific versions of major dependencies you posted, and have included the `pyproject.toml`, `poetry.lock`, and the output of `pip list`. If you are able to run in a virtual environment using python 3.10 with the attached package versions, or reinstall using the new poetry lockfile, you should be able to pull data without error.

If the issue persists, please feel free to reopen this issue.

Thanks and have an excellent rest of your day!
[list.txt](https://github.com/user-attachments/files/16150443/list.txt)
[poetry.lock.txt](https://github.com/user-attachments/files/16150454/poetry.lock.txt)
[pyproject.toml.txt](https://github.com/user-attachments/files/16150455/pyproject.toml.txt)
